service: auth-server
app: meet
provider:
  name: aws
  runtime: nodejs22.x
  region: eu-central-1
  timeout: 30 
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: /get-auth-url
          method: get
          cors: true
  
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: /get-access-token/{code}
          method: get
          cors: true
  
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: /get-calendar-events/{access_token}
          method: get
          cors: true
